language: python
python:
    - '2.7'
install:
    - 'pip install -r requirements.txt'
    - 'pip install -r requirements.test.txt'
script:
    - 'py.test --cov=pycco tests/'
after_success:
    - coveralls
